---
services:
  qbittorent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: container:gluetun
    environment:
      - WEBUI_PORT=8088
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/qbittorrent/config:/config
      - /media/external/downloads:/downloads