---
services:
  radarr-uhd:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-uhd
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/radarr-uhd/config:/config
      - /media/external/downloads:/downloads #optional
      - /media/external:/local-media #optional

  radarr-hd:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-hd
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/radarr-hd/config:/config
      - /media/external/downloads:/downloads #optional
      - /media/external:/local-media #optional