services:
  myst:
    image: mysteriumnetwork/myst:latest
    container_name: myst
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - /srv/mysterium/mysterium-node:/var/lib/mysterium-node
    restart: unless-stopped
    command: ["service", "--agreed-terms-and-conditions"]