services:
  myst:
    image: mysteriumnetwork/myst:latest
    container_name: myst
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped
    volumes:
      - /srv/mysterium/mysterium-node:/var/lib/mysterium-node
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - service
      - --agreed-terms-and-conditions