services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    restart: unless-stopped
    volumes:
      - /media:/media
      - /srv/audiobookshelf/config:/config
      - /srv/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/London
