---
services:
  jellyfin:
    image: jellyfin/jellyfin:10:10:0
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096
    group_add:
      - "993"
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /media:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: 'unless-stopped'
    environment:
      - TZ=Europe/London