---
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 36944:36944
      - 36944:36944/udp # port generated in gluten/info/forwarded_port
      - 8088:8088 # qbittorrent
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 9696:9696 # prowlarr
    volumes:
      - /srv/gluetun:/gluetun
      - /srv/gluetun/info:/tmp/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=Etc/UTC
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16 # Internal network