---
services:
  sonarr-uhd:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-uhd
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/sonarr-uhd/config:/config
      - /mnt/shared-media/media/tv-uhd:/tv #optional
      - /media/external/downloads:/downloads #optional

  sonarr-hd:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-hd
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/sonarr-hd/config:/config
      - /mnt/shared-media/media/tv-hd:/tv #optional
      - /media/external/downloads:/downloads #optional