---
services:
  sonarr-uhd:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-uhd
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PORT=8988 #optional
    volumes:
      - /srv/sonarr-uhd/config:/config
      - /media/external/downloads:/downloads #optional
      - /media:/local-media #optional

  sonarr-hd:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-hd
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PORT=8989 #optional
    volumes:
      - /srv/sonarr-hd/config:/config
      - /media/external/downloads:/downloads #optional
      - /media:/local-media #optional