include:
  - ./gluetun/docker-compose.yml 
  - ./qbittorrent/docker-compose.yml 
  - ./prowlarr/docker-compose.yml 
  - ./radarr/docker-compose.yml 
  - ./sonarr/docker-compose.yml 
services:
  qbittorrent:
    depends_on: 
      - gluetun
  prowlarr:
    depends_on: 
      - gluetun
  radarr:
    depends_on: 
      - gluetun
  sonarr:
    depends_on: 
      - gluetun