---
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
     - NET_ADMIN
    ports:
     - 35026:35026
     - 35026:35026/udp # port generated in gluten/info/forwarded_port
     - 8088:8088 # qbittorrent
     - 9696:9696 # prowlarr
     - 7878:7878 # radarr
     - 8989:8989 # sonarr
    volumes:
     - /srv/gluetun:/gluetun
     - /srv/gluetun/info:/tmp/gluetun
    devices:
     - /dev/net/tun:/dev/net/tun
    environment:
     - TZ=Etc/UTC
     - VPN_SERVICE_PROVIDER=custom
     - VPN_TYPE=wireguard
     - VPN_PORT_FORWARDING=on
     - VPN_PORT_FORWARDING_PROVIDER=protonvpn
     - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16 # Internal network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
     - WEBUI_PORT=8088
     - TZ=Etc/UTC
     - PUID=1000
     - PGID=1000
    volumes:
     - /srv/qbittorrent/config:/config
     - /media/external/downloads:/downloads
    depends_on: 
     - gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=Etc/UTC
    volumes:
     - /srv/prowlarr/config:/config
    depends_on: 
     - gluetun

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=Etc/UTC
    volumes:
     - /srv/radarr/config:/config
     - /media/external/movies:/movies #optional
     - /media/external/downloads:/downloads #optional
    depends_on: 
     - gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=Etc/UTC
    volumes:
     - /srv/sonarr/config:/config
     - /media/external/tv:/tv #optional
     - /media/external/downloads:/downloads #optional
    depends_on: 
     - gluetun