---
 services:
  readarr:
     image: lscr.io/linuxserver/readarr:develop
     container_name: readarr
     network_mode: container:gluetun
     restart: unless-stopped
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Etc/UTC
     volumes:
       - /srv/readarr/config:/config
       - /media/external/downloads:/downloads #optional
       - /media:/local-media #optional