---
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /srv/nginx-proxy-manager/data:/data
      - /srv/nginx-proxy-manager/letsencrypt:/etc/letsencrypt