---
 services:
   lidarr:
     image: lscr.io/linuxserver/lidarr:latest
     container_name: lidarr
     network_mode: container:gluetun
     restart: unless-stopped
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Etc/UTC
     volumes:
       - /srv/lidarr/config:/config
       - /media/external/downloads:/downloads #optional
       - /media:/local-media #optional