---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.0
    container_name: qbittorrent
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
      - WEBUI_PORT=8088
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/qbittorrent/config:/config
      - /media/external/downloads:/downloads