---
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    user: 1000:1000
    ports:
      - 8096:8096
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - type: bind
        source: /mnt/e/media
        target: /media
    restart: 'unless-stopped'
    environment:
      - TZ=Europe/London
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]