---
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - media-share-two:/media:ro
    restart: 'unless-stopped'
    environment:
      - TZ=Europe/London
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  media-share-two:
    driver_opts:
      type: cifs
      o: "username=ubuntu,password=ubuntu,ro,uid=1000,gid=1000"
      device: //192.168.68.63/media-share-two