services:
  db:
    image: mariadb:10.11
    command: --transaction-isolation=READ-COMMITTED
    restart: always
    volumes:
      - /srv/nextcloud/config/mysql:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=ahx1Tho2
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env
    networks:
      - nginx-proxy-manager

  redis:
    image: redis:alpine
    restart: always
    networks:
      - nginx-proxy-manager

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - /srv/nextcloud/config/html:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - nginx-proxy-manager

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - /srv/nextcloud/config/html:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - nginx-proxy-manager

networks:
  nginx-proxy-manager:
    external: true