services:
  nextcloud-db:
    image: mariadb:10.11
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - /srv/nextcloud/mysql:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=ahx1Tho2
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      - TZ=Europe/London
    env_file:
      - db.env
    networks:
      - nginx-proxy-manager

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - /srv/nextcloud/redis/data:/data:z
    networks:
      - nginx-proxy-manager

  nextclound-app:
    image: nextcloud:apache
    container_name: nextcloud-app
    restart: unless-stopped
    volumes:
      - /srv/nextcloud/html:/var/www/html:z
      - /mnt/cloud/nextcloud/data:/var/www/html/data:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    environment:
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
      - TZ=Europe/London
    env_file:
      - db.env
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nginx-proxy-manager

  nextcloud-cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    restart: unless-stopped
    volumes:
      - /srv/nextcloud/html:/var/www/html:z
      - /mnt/cloud/nextcloud/data:/var/www/html/data:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    environment:
      - TZ=Europe/London
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nginx-proxy-manager

  nextcloud-talk-hpb:
    container_name: nextcloud-talk-hpb
    image: nextcloud/aio-talk:latest
    init: true
    ports:
      - 3478:3478/tcp
      - 3478:3478/udp
    environment:
      - NC_DOMAIN=nextcloud.smartypants.uk
      - TALK_HOST=signal.smartypants.uk
      - TURN_SECRET=4c35c39409e5f2eaf6325838d3f8d4aded167ff1d1e28f746d36cffe07ff02bf
      - SIGNALING_SECRET=9d63bd1243561366f3a57a0568a8c18b8f1ad08d2e710eefd66d37c2f657ddca
      - TALK_PORT=3478
      - INTERNAL_SECRET=c2386978c6ca108f948e5f2e168bb177e8fd6c423e6815eb58a7f9e4d8ab585a
      - TZ=Europe/London
    restart: unless-stopped
    networks:
      - nginx-proxy-manager

  collabora:
    container_name: nextcloud-collabora
    image: collabora/code:latest
    cap_add: 
     - MKNOD
    environment: 
     - domain=nextcloud.smartypants.uk
     - username=nextcloud
     - password=ua6cheoZ
     - TZ=Europe/London
     - extra_params=--o:ssl.enable=true
    restart: unless-stopped
    networks:
      - nginx-proxy-manager

networks:
  nginx-proxy-manager:
    external: true