services:
  nextcloud-db:
    image: mariadb:10.11
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - /srv/nextcloud/mysql:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=ahx1Tho2
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env
    networks:
      - nginx-proxy-manager

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    networks:
      - nginx-proxy-manager

  collabora:
      image: collabora/code:latest
      container_name: collabora
      restart: unless-stopped
      networks: 
        - nginx-proxy-manager
      environment:
        - PUID=1000
        - PGID=1000
        - password=Aishi0Go 
        - username=nextcloud
        - domain=nextcloud.smartypants.uk
      #  - extra_params=--o:ssl.enable=true # Use if have ssl. You should.
      ports:
        - 9980:9980

  nextclound-app:
    image: nextcloud:apache
    container_name: nextcloud-app
    restart: always
    volumes:
      - /srv/nextcloud/html:/var/www/html:z
      #- /mnt/cloud/nextcloud:/var/www/html/data
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    environment:
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
    env_file:
      - db.env
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nginx-proxy-manager
    ports:
      - 8081:80

  nextcloud-cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    restart: always
    volumes:
      - /srv/nextcloud/html:/var/www/html:z
      #- /mnt/cloud/nextcloud:/var/www/html/data
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nginx-proxy-manager

networks:
  nginx-proxy-manager:
    external: true