services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/heimdall/config:/config
    ports:
      - 9980:80
      - 99443:443
    restart: unless-stopped
