services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports: 
      - "11434:11434"
    pull_policy: always
    tty: true
    volumes:
      - ollama:/root/.ollama
    networks:
      - ai-network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: 
                - gpu
    
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    networks:
      - ai-network
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      ENABLE_WEB_SEARCH: "True"
      WEB_SEARCH_ENGINE: "searxng"
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
      searxng:
        condition: service_started

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./searxng:/etc/searxng
    networks:
      - ai-network
    environment:
      - BASE_URL=http://searxng:8080/

volumes:
  ollama:
  open-webui:
  searxng:

networks:
  ai-network:
    name: ai-network
    driver: bridge